name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    name: Build on ubuntu-18.04 armv7
    steps:
    - uses: actions/checkout@v3
    - name: update 
      run: apt-get install ndk-build
    #- uses: uraimo/run-on-arch-action@v2
      #name: Run commands
      #id: runcmd
      #with:
       #arch: armv7
       #distro: ubuntu18.04
    - name: make
      run: make install
    - name: uploaded
      uses: actions/upload-artifact@v4
      with:
        name: mmc
        path: /usr/local/bin/mmc
